### ISSUE TITLE
Small correction to support onScroll

### ISSUE THREAD

**Issue by dcesca** [johankladder/react-native-collapsible-header-components#1]
Hi, I noticed that onScroll event didn't fire.
Modifing the function this way it does:

_getCollapsibleViewProps = () => {
        let {collapsibleHeaderHeight,onScroll} = this.props;

        return {
            contentContainerStyle: {paddingTop: collapsibleHeaderHeight},
            scrollEventThrottle: 1,
            onScroll: Animated.event(
                [
                    {
                        nativeEvent: {
                            contentOffset: {y: this.state.scrollY}
                        }
                    }
                ],
                {useNativeDriver: true, listener: onScroll}
            )
        }
    }

**Comment by johankladder** [comment]
Hello dcesca,

I've added this now to the 0.2.2 version. Enjoy! :)
